### ISSUE TITLE
Twemoji does not provide an export named 'EmojiDefinition' (anonymous) @ nuxt.js:97

### ISSUE THREAD

**Issue by williamkmp** [Yizack/nuxt-twemoji#1]
I had just install nuxt-twemoji in my nuxt 3 project, in one of the pages i wanted to test out the <Twemoji/> component.
Instead I encountered an error while opening the page in the browser, here is the browser error log:

![image](https://github.com/Yizack/nuxt-twemoji/assets/81504006/1d1a4c36-1a98-4b5e-bb7a-3767fee1a5f4)

Here is the vue code

```
<script setup lang="ts">
import * as Emoji from 'nuxt-twemoji/emojis';

</script>

<template>
    <div class="h-full w-full p-5">
        <UContainer>
            <Twemoji :emoji="Emoji.twSmilingFace" />
            <p>Hello world</p>
        </UContainer>
    </div>
</template>
```

I install the twemoji using `npm install --save-dev nuxt-twemoji`
I also already added `nuxt-twemoji` inside _nuxt.config.ts_  modules, am I missing any steps? If so I am sorry 🙏

I am using nuxt version nuxt@3.8.2 and nuxt-twemoji version 3.3.5

**Comment by TheoSigaud** [comment]
I also have the same problem

**Comment by williamkmp** [comment]
I may have found the problem, inside `Twemoji.vue` component the EmojiDefinition type needed to be explicitly imported due to nnuxt 3.8.0 update

**Comment by Yizack** [comment]
Appreciate you thanks!
